version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: claude2ds
    main: .
    binary: claude2ds
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

archives:
  - id: default
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

kos:
  - id: claude2stream
    build: claude2ds
    repository: ghcr.io/broady/claude2stream
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{.Version}}"
      - "{{if not .Prerelease}}latest{{end}}"
    bare: true
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    sbom: none
